{
  try {
    callback.onFailure((Throwable)this.result);
  }
 catch (  Throwable ex) {
  }
}
