{
  mockCollaborator.noArgsOnRuntimeExceptionMatch();
  mockControl.replay();
  try {
    this.testBean.exceptional(new RuntimeException());
    fail("should throw exception");
  }
 catch (  Throwable t) {
  }
  mockControl.verify();
}
