{
  final Exception expectedException=new Exception();
  MethodInterceptor mi=new MethodInterceptor(){
    public Object invoke(    MethodInvocation invocation) throws Throwable {
      throw expectedException;
    }
  }
;
  AdvisedSupport pc=new AdvisedSupport(new Class[]{ITestBean.class});
  pc.addAdvice(ExposeInvocationInterceptor.INSTANCE);
  pc.addAdvice(mi);
  mockTargetSource.setTarget(new Object());
  pc.setTargetSource(mockTargetSource);
  AopProxy aop=createAopProxy(pc);
  try {
    ITestBean tb=(ITestBean)aop.getProxy();
    tb.exceptional(expectedException);
    fail("Should have thrown exception raised by interceptor");
  }
 catch (  Exception thrown) {
    assertEquals("exception matches",expectedException,thrown);
  }
}
