{
  callBack.runTestMethod(testResult);
  this.testException=testResult.getThrowable();
}
